INTRO_LINES = [
    "Beware the demon!",
    "Darkness falls!",
    "Darkness is coming!",
    "Death is coming!",
    "Peace is overrated!",
    "Prepare for a tale of blood and betrayal!",
    "Prepare for a tale of blood and mystery!",
    "Prepare to get spooky!" "The clock is ticking...",
    "The demon is among us!",
    "The demon is one of them!",
    "The demon is one of us!",
    "The demon is one of you!",
    "The game is afoot!",
    "The game is ahoof!",
    "The moon is full!",
    "The moon is high!",
    "The moon is out!",
    "The moon is red!",
    "The night is dark!",
    "The night is long!",
    "The night is young!",
    "The night is yours!",
    "The night will be long!",
    "The night will be yours to command!",
    "The night will be yours!",
    "The town is doomed!",
    "The town is in danger!",
    "The town is in peril!",
    "The town is in trouble!",
    "There is a demon among us!",
    "There will be blood!",
    "Trust no one!",
    "Watch out for the demon!",
    "Watch your back!",
    "Where is the demon?",
    "Where shall we begin?",
    "Who is the demon?",
    "Who will survive?",
]
